# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: New Blog

# Short description (goes below the title; it will also be used in the RSS feed)
description: For notes.

# Your name, as you want it to appear underneath each post and in the footer
author: kiro

# Your email if you want it to be linked on the contact page
author_email: guankiro@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

social:
  github: kirokuan
  stackoverflow: '1330995'
  linkedin: ''
  instagram: ''
  lastfm: ''
  rss: feed.xml

baseurl: /jekyll
google_analytics_key: UA-75073217-1
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://kirokuan.github.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
#markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

comments : true
disqus : kirokuan
# How many articles do you wish to appear on the front page:
paginate: 10
gems: [jekyll-paginate,jekyll-tagging]
tag_page_layout: tag_index
tag_page_dir: tag
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
